## Plugin Configurations

liquid:
  error_mode: strict

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true

sass:
  style: compressed


## Globals

url:        https://saswat.padhi.me
baseurl:
repository: SaswatPadhi/saswatpadhi.github.io
permalink:  pretty

title:      'Vineeth Sagar'
timezone:   'America/Chicago'

author:
  name:     'Vineeth Sagar Thapeta'
  link:     https://saswat.padhi.me
  photo:
    alt:    'Avatar from GitHub'
      #remote: https://avatars3.githubusercontent.com/u/1577944
    local: assets/img/photos/headshot.jpeg

github: [metadata]

## Theme and Layout

default_icon:
  award: award
  position: id-badge
  publication: file-alt
  service: user-cog
  talk: microphone
  teaching: chalkboard-teacher

default_highlight:
  award: accent
  position: medium-accent
  publication: highlight

# Defaults:
# ---------
# theme:
#   tooltips:    enabled
#   hover_light: enabled
#
# fonts:
#   base: Noto Sans
#   head: Montserrat
#   mono: Ubuntu Mono
#
# layout:
#   header:
#     style: scroll # (can be: scroll | fixed | disabled)
#   footer:
#     style: scroll # (can be: scroll | fixed | disabled)

layout:
  header:
    style: fixed

topmenu:
  Resume:
    cv:
      local: CV.md
    LinkedIn:
      url: https://www.linkedin.com/in/vineeth-sagar-6186a8118/
      title: LinkedIn
      icon:  fab fa-linkedin-in
  Main:
    publications:
      local: publications.md
    GitHubProfile:
      url:   https://github.com/vsag96
      title: GitHub
      icon:  fab fa-github

collections:
  blogposts:
    output: true
    permalink: 'blog/:path.html'
  publications:
    output: true
  slides:
    output: true
    permalink: '/:collection/:path.html'
  updates:
    output: false

defaults:
  - scope:
      path: ''
      type: slides
    values:
      layout: slide
  - scope:
      path: ''
      type: blogposts
    values:
      layout: blogpost
  - scope:
      path: ''
      type: publications
    values:
      layout: article
